"""Assemble the same self-contained, credential-free site for preview and Pages."""

from __future__ import annotations

import shutil
from pathlib import Path
from tempfile import TemporaryDirectory

from phistory.render import render_index
from phistory.site import render_site
from phistory.translation.assets import TranslationAssets

PUBLIC_FILES = ("CNAME", ".nojekyll", "robots.txt", "sitemap.xml", "docs/screenshot.png")
PUBLIC_GLOBS = ("docs/*.md", "docs/agent-icons/*.md", "docs/agent-icons/*.png", "docs/agent-icons/*.svg")
BUILD_MARKER = ".phistory-site"


def build_site(root: Path, output: Path) -> None:
    """Publish explicit archive assets; never copy caches, config, or the working tree."""
    root, output = root.resolve(), output.resolve()
    base = root.parent
    if not root.is_dir():
        raise ValueError(f"capture root does not exist: {root}")
    inputs = (root, base / "translations", base / "docs")
    if output == base or any(output.is_relative_to(path) or path.is_relative_to(output) for path in inputs):
        raise ValueError("site output must be separate from archive, dictionary and documentation directories")
    if output.exists() and not (output / BUILD_MARKER).is_file() and any(output.iterdir()):
        raise ValueError(f"site output is not an empty directory or a previous Phistory build: {output}")

    output.parent.mkdir(parents=True, exist_ok=True)
    # Complete the build before replacing a previous preview, including obsolete assets.
    with TemporaryDirectory(prefix=".phistory-site-", dir=output.parent) as temporary:
        public = Path(temporary)
        captures = public / "captures"
        captures.mkdir()
        for name in ("prompt.md", "trace.jsonl", "meta.json"):
            for path in root.glob(f"*/*/variants/*/{name}"):
                _copy(path, captures / path.relative_to(root))
        for name in ("candidates.json", "prompts.json", "prompts.md"):
            for path in root.glob(f"*/*/static/{name}"):
                _copy(path, captures / path.relative_to(root))
        for path in (base / "translations").glob("zh-CN/*/runtime.json"):
            _copy(path, public / path.relative_to(base))
        for name in PUBLIC_FILES:
            if (path := base / name).is_file():
                _copy(path, public / name)
        for pattern in PUBLIC_GLOBS:
            for path in base.glob(pattern):
                _copy(path, public / path.relative_to(base))

        render_index(captures, public / "README.md")
        render_site(captures, public / "index.html", translations=TranslationAssets(public).for_row)
        (public / ".nojekyll").touch()
        (public / BUILD_MARKER).write_text("Generated by phistory build-site.\n", encoding="utf-8")
        if output.exists():
            shutil.rmtree(output)
        public.rename(output)


def _copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
